### ISSUE TITLE
Telemetry gathering causes obnoxious popups and cannot be disabled

### ISSUE THREAD

**Issue by s100** [ibm-telemetry/telemetry-js#250]
**Description**

I find the fact that we have to opt *out* of having this telemetry gathered highly questionable. But honestly what I find irritating about this package is that it briefly pops up an empty shell window when it runs which obstructs the rest of my screen and steals focus. This is on Windows.

We don't use `@ibm/telemetry-js` directly, but we do use `@carbon/react` which has numerous dependencies which use `@ibm/telemetry-js`:

```
C:\Users\s100\Downloads>npm list @ibm/telemetry-js
Downloads@ C:\Users\s100\Downloads
`-- @carbon/react@1.59.0
  +-- @carbon/feature-flags@0.20.0
  | `-- @ibm/telemetry-js@1.5.2 deduped
  +-- @carbon/icons-react@11.43.0
  | +-- @carbon/icon-helpers@10.48.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | `-- @ibm/telemetry-js@1.5.2 deduped
  +-- @carbon/layout@11.22.0
  | `-- @ibm/telemetry-js@1.5.2 deduped
  +-- @carbon/styles@1.59.0
  | +-- @carbon/colors@11.22.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | +-- @carbon/grid@11.23.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | +-- @carbon/motion@11.18.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | +-- @carbon/themes@11.36.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | +-- @carbon/type@11.27.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | `-- @ibm/telemetry-js@1.5.2 deduped
  `-- @ibm/telemetry-js@1.5.2
```

What this means is that when I `npm install @carbon/react`, this empty shell window pops up **eleven times!** It's exceedingly annoying and blocks my workflow for 5-6 seconds.

[According to the documentation](https://github.com/ibm-telemetry/telemetry-js?tab=readme-ov-file#opting-out-of-ibm-telemetry-data-collection) we can set the environment variable `IBM_TELEMETRY_DISABLED=true` but **this doesn't work.** How do we opt out of this?

**Steps to reproduce**

On Windows:

```cmd
set IBM_TELEMETRY_DISABLED=true
npm install @carbon/react
```

Then watch.

**Comment by mattrosno** [comment]
Hi @s100 - thank you for reporting this. We confirmed that even though the empty shell windows were popping up, the opt-out continued to work and no data was collected. (Also, if not opted out, data is only collected in CI environments, never in a local environment.)

We have a PR started (linked above) that adds some better guidance for how to opt out when using Windows, with a fix to prevent the background process from spawning shell windows.
