### ISSUE TITLE
Link to telemetry feedback is broken

### ISSUE THREAD

**Issue by timo** [ibm-telemetry/telemetry-js#273]
https://github.com/ibm-telemetry/telemetry-js/blob/4740cae7841ab086c1ff63371cadb11e74f147b1/.github/ISSUE_TEMPLATE/config.yml#L7

When creating a new issue, you are first presented with a few choices, including to "Share your feedback with the Telemetry squad.", however the link it takes you to is the github discussions page for this repository which is not enabled.

**Comment by mattrosno** [comment]
@timo not sure how we missed that - thanks for reporting! We've enabled discussions for this repository: https://github.com/ibm-telemetry/telemetry-js/discussions
