### ISSUE TITLE
De-identification / anonymization of packages is not sufficient.

### ISSUE THREAD

**Issue by timo** [ibm-telemetry/telemetry-js#274]
Using just a single round of sha256 is not enough to provide any meaningful amount of anonymity.

A single round of sha256 is computed very quickly. There is even an npm package from jsDelivr that has all names of npm packages in a handy 90 megabyte json file. Even if you program it very inefficiently, it doesn't take longer than a minute to generate hashes of every package name including splitting at "/" and taking the first part (usually this would be the "owner"). In fact, it's so easy and runs so quickly that I did just that.

I have here a roughly 500 megabytes big (uncompressed) text file with hashes like this:

```
000003dfd8c337f4c5c77863b06483c84ad2f08c7d5a9a9508bac85ba55687dd=@kolearn/common
00000a3e4f508b5c6039b9abd9c9585c1915f7f1fa37a215f513b28280914210=@zalastax/nolb-randomh
00000b52ecba65283aca8e60777a7c7a00057bb7ddb2a8de0d6e2cea90fe1aa6=test-dsr-tonal-airer-cover-slams
00000b6b96f39cf36283c045eb98ad3a925931033d1e29648ecd8d98b034c0cb=@zalastax/nolb-github-b
00000f10a14daa8c9b810d196800cce5df472893da402571343395925b44a555=s3t
000015e15e0a1041326ee5a888100f7d1e38a278ffe8b08745a3bf68a3732549=@melkornms/chart.js
0000167ce92b5d24d9cf43e8a8da3d54094352d554fbf3a9c94c010d60543152=react-native-mrz-library
000017964c17674ee722344a4945e497a896d96c2b1176e4676d119a2c13f846=react-codemirror-runmode
000019311be764bad7a0e3368d0974666f21db1216decf58658e55b4fc392ba9=webfunc_jsonformatter
[...]
016eb55a0b37257c890f3450934c3c7a274969beea296223f8df81ccda717422=@hyper.fun/fluentui-emoji-safety-pin-color
016ebd07c8d2bc981ec56d47a0a7e0a4b4011c19ba17ad504f995545edd5193f=@dwcore/intrinsic
016ebeb25a6bd61e6405513effc94ce74432151f9ee7fa5435b1811e4cb3ad8f=@ibm-functions/shell-local-plugin
016ebff0b01ff86912a45a4d9872a8435e28503e4565b2f3e67271771f002fdf=@jedisct1/charm
016ec2970395a1f51280ea61c4ee5084f0cc08ac7c8d93ab3ddd6754808ce91c=fib44
016ec89cee8694bda34e196e46da0419503eedf773514eab2278c731724c380c=tapok
[...]
19c7c34e9fb4d2a01a8a04b286d9347555137afa95724531913f29a091deb759=@pahud/aws-serverless-patterns
19c7ca08f2e4135b650f9fae7536069842f57ab0e2823857577f96e38df77dc0=awesome-components
19c7da3d2bccf147f9cdc65408bf3b48f405f936a87d0f16803f6ff538962d31=@ibm/telemetry-js
19c7e1823968c4f9bb749fd4f7c18aa3428e7c2749b559715f0710d1d6ef376f=@taboola/rnt-dev
19c7e2c16317cb5332acfc1dc918570e69a54af09a396ed6d65adccb1f93d38e=@jswork/next-ng-blank-merge
[...]
ffffddd4906b0c693432ae4a604a571f061914d507e617d71aa2a96ae3a8521a=@marco.cabrejos
fffff5d8abbd533ebe3677f633803a5e3a6040fce8aa8f84992f300ac2e50a68=@kitbag/events
fffff72b384d95d694b6276458d6045d732275a5f761ad41d654dbed69b144d5=webpack5-qcdn-plugin
fffff73c5899fa2886b560fc6c6a932d66686463d61b90d35616afb0a6e2b43b=task-drawer
```

For anything that's not public, when you're looking for the text that gives one out of ~a few thousand hashes you get into "password cracker" territory where lots of ink has been spilled, but if you have an educated guess what a piece of telemetry data refers to, you'll probably have a good chance to figure it out.

It does not fill me with confidence when the work needed to go from a hash to a package name and owner username / owner organization name is so completely trivial.

At the very least, I would call this particular wording in the readme incorrect, though I'm sure it was not meant to be deceiving:

> When data is to be de-identified, it is hashed using the SHA-256 cryptographic function, meaning an instrumented package owner can query for specific known names/values but can never recover original values from the stored data in the database.
> 
> When data is to be anonymized, it is redacted/substituted in a way where its original value can never be recovered, and there is no meaningful way to query the data to ascertain its value.

If you are not sure what would be suitable to replace sha256 with, I would suggest using a hash that is meant to resist brute-forcing, for example by requiring the use of a nontrivial amount of RAM to correctly calculate, and salting the value that goes into the hash from each key (package name, owner name, etc) with a different prefix, so that `"package_name": "ibm", "owner_name": "ibm"` results in `"package_name": "blabla", "owner_name": "something that is not blabla"` and not `"package_name": "blabla", "owner_name": "blabla"`

**Comment by mattrosno** [comment]
Hi @timo - thank you for the issue. We'll revisit our decision to use SHA-256. Should that result in any change to our hashing strategy to de-identify data, we'll be sure to follow up. In addition to npm dependencies, here is what else is getting de-identified with SHA-256: https://github.com/ibm-telemetry/telemetry-js?tab=readme-ov-file#what-data-gets-collected

Here are opt-out instructions, should you want to prevent IBM Telemetry data collection from your project going forward: https://github.com/ibm-telemetry/telemetry-js?tab=readme-ov-file#opting-out-of-ibm-telemetry-data-collection
