### ISSUE TITLE
MongoCarbon

### ISSUE THREAD

**Issue by n-for-all** [ibm-telemetry/telemetry-js#286]
**Repository**

> What is your package's GitHub repository? Please provide a URL, including the path if the
> repository is a monorepo.

https://github.com/n-for-all/mongocarbon

**Registry**

mongocarbon

> Where is your package published? Please provide a URL.

https://www.npmjs.com/package/mongocarbon

I need a project id for telemetry

thanks

**Comment by mattrosno** [comment]
Hi @n-for-all - IBM Telemetry is only being used to instrument IBM and Carbon Design System projects. As such, I recommend that you uninstall the [dependency in your repository](https://github.com/n-for-all/mongocarbon/blob/main/package.json#L29), as this package won't work without a project ID.
