### ISSUE TITLE
Telemetry opt-out for all users of a project?

### ISSUE THREAD

**Issue by joepie91** [ibm-telemetry/telemetry-js#289]
Hi, according to the README of this project, it is possible to disable telemetry by setting an environment variable - however, this would only work to disable telemetry on my own system.

If I am working on an open-source project which includes an IBM library, is there a way to apply the opt-out for all those people that my own project is distributed to? As they are unlikely to be interacting with the IBM libraries directly, the telemetry would likely get overlooked.

**Comment by mattrosno** [comment]
Hi @joepie91 - thank you for your question. How are you distributing your project? Are you publishing your own npm package or is your project distributed through GitHub forking / cloning?

If the latter, what about committing the initial `.env` file that includes the opt-out environment variable [documented here](https://github.com/ibm-telemetry/telemetry-js?tab=readme-ov-file#opting-out-of-ibm-telemetry-data-collection).
